
services:
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/laravel
        depends_on:
            - php
            - mysql
    php:
        container_name: php
        build:
            context: ./docker/Dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - .:/var/www/laravel
        depends_on:
            -   mysql
    mysql:
        container_name: mysql
        image: mysql:8.1
        ports:
            -  3316:3306
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/logs:/var/log/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: craft-store
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin

    postgres:
        container_name: postgres
        image: postgres:17.2
        ports:
            - 5432:5432
        volumes:
            - ./docker/postgredb/data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: craft-store
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            PGDATA: /var/lib/postgresql/data/pgdata
    elasticsearch:
        container_name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
        ports:
            -   9300:9200
