<?php

namespace App\Facades;

use Illuminate\Support\Facades\Facade;

class FilterFactory extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'filterFactory'; // TODO: Change the autogenerated stub
    }
}
