<?php

namespace App\Facades;

use Illuminate\Support\Facades\Facade;

class UserActivityLogger extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'logactivity'; // TODO: Change the autogenerated stub
    }
}
